### PR TITLE
Multi picture multi select plug in docs example

### PR DESCRIPTION
**Pull request by lbai001**
creates multi picture plugin
creates multi select plugin
creates docs for multi picture plugin
creates docs for multi select plugin
creates example for multi picture plugin
creates example for multi select plugin

### CODE REVIEW

**Comment by RobAWilkinson** [comment]
@jodeleeuw any progress on this?

**Comment by jodeleeuw** [comment]
Didn't realize you were waiting on me. Sorry about that! Will get to this asap, but have some deadlines early next week that I need to meet first.

**Comment by RobAWilkinson** [comment]
@jodeleeuw no worries, finished with stuff at l3atbc and just wanted to get this in the main repo so we could point to the main jsPsych rather than the fork

**Comment by jodeleeuw** [comment]
Made changes to this via #344, will merge from there.

**Pull request closed without merging**
