### PR TITLE
Add survey-multi-choice plugin

### PR DESCRIPTION
**Pull request by shamrt**
Adds a simple multiple choice survey plugin. Much like the survey-likert plugin, the subject is presented questions and selects a single option.

`/docs` has been updated with the new plugin documentation. I've also added an example file in `/tests&examples`.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
This looks awesome. I'll review it more carefully soon. Thank you! 

:+1: :+1:

**Comment by shamrt** [comment]
I suggest you add one more line to the jsPsych CSS file:

    .jspsych-survey-multi-choice-horizontal .jspsych-survey-multi-choice-option {
      ...
      vertical-align: top;
    }

If a person uses line-breaks (`<br>`) in their option labels, e.g.:

    var likert_scale_2 = [
      "1<br>Significantly<br>Below Average",
      "2",
      "3",
      "4<br>Average",
      "5",
      "6",
      "7<br>Significantly<br>Above Average"
    ];

then the radio bullets will all align at the top.

**Comment by shamrt** [comment]
I've added a fix and an improvement to the plugin.

**Comment by shamrt** [comment]
The latest update was a requirement of a project that I'm working on. Feel free to take it or leave it.

**Comment by jodeleeuw** [comment]
merged this via #205

**Pull request closed without merging**
